# Generated by Django 4.2.6 on 2023-12-08 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0003_servicetb'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationtb',
            name='Status',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
