# Generated by Django 4.2.6 on 2023-12-20 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0004_registrationtb_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingTb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserId', models.CharField(max_length=50)),
                ('UserName', models.CharField(max_length=50)),
                ('ServiceId', models.CharField(max_length=50)),
                ('ServiceName', models.CharField(max_length=50)),
                ('WorkerId', models.CharField(blank=True, max_length=50, null=True)),
                ('WorkerName', models.CharField(blank=True, max_length=50, null=True)),
                ('Date', models.CharField(max_length=50)),
                ('Time', models.CharField(max_length=50)),
                ('Status', models.CharField(max_length=50)),
            ],
        ),
    ]
