# Generated by Django 4.2.6 on 2023-12-20 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0006_bookingtb_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicetb',
            name='Price',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
