# Generated by Django 4.2.6 on 2023-12-20 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0011_servicetb_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicetb',
            name='CategoryImage',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
