# Generated by Django 4.2.6 on 2023-12-29 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0014_categorytb_remove_servicetb_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categorytb',
            old_name='Category',
            new_name='CategoryName',
        ),
    ]
