# Generated by Django 4.2.6 on 2023-12-29 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0015_rename_category_categorytb_categoryname'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicetb',
            name='CategoryName',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='projectapp.categorytb'),
            preserve_default=False,
        ),
    ]
