# Generated by Django 4.2.6 on 2023-12-29 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0016_servicetb_categoryname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicetb',
            old_name='CategoryName',
            new_name='CategoryId',
        ),
    ]
