# Generated by Django 4.2.6 on 2024-01-02 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0017_rename_categoryname_servicetb_categoryid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicetb',
            name='Description',
            field=models.CharField(max_length=5000),
        ),
    ]
