# Generated by Django 4.2.6 on 2024-01-02 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0018_alter_servicetb_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicetb',
            name='Rating',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
