# Generated by Django 4.2.6 on 2024-01-07 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0020_remove_bookingtb_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingtb',
            name='ServiceImage',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
